/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IDEXGovernance, IDEXGovernanceInterface } from "../../interfaces/IDEXGovernance.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "actionId",
        "type": "bytes32"
      }
    ],
    "name": "ActionCancelled",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "actionId",
        "type": "bytes32"
      }
    ],
    "name": "ActionExecuted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "actionId",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "executeAfter",
        "type": "uint256"
      }
    ],
    "name": "ActionQueued",
    "type": "event"
  }
] as const;

  export class IDEXGovernance__factory {
    static readonly abi = _abi;
    static createInterface(): IDEXGovernanceInterface {
      return new Interface(_abi) as IDEXGovernanceInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IDEXGovernance {
      return new Contract(address, _abi, runner) as unknown as IDEXGovernance;
    }
  }
  