/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFundingPool } from './IFundingPool.js';
export type { MockVotingSystem } from './MockVotingSystem.js';