/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface AirdropInterface extends Interface {
    getFunction(nameOrSignature: "amountPerUser" | "canClaim" | "claim" | "claimedCount" | "hasClaimed" | "maxUsers" | "token"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "TokensAirdropped"): EventFragment;

    encodeFunctionData(functionFragment: 'amountPerUser', values?: undefined): string;
encodeFunctionData(functionFragment: 'canClaim', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'claim', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimedCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'hasClaimed', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'maxUsers', values?: undefined): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'amountPerUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'canClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimedCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasClaimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxUsers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
  }

  
    export namespace TokensAirdroppedEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint];
      export interface OutputObject {user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Airdrop extends BaseContract {
    
    connect(runner?: ContractRunner | null): Airdrop;
    waitForDeployment(): Promise<this>;

    interface: AirdropInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    amountPerUser: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    canClaim: TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    claim: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    claimedCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    hasClaimed: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    maxUsers: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'amountPerUser'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'canClaim'): TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'claim'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimedCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hasClaimed'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'maxUsers'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'TokensAirdropped'): TypedContractEvent<TokensAirdroppedEvent.InputTuple, TokensAirdroppedEvent.OutputTuple, TokensAirdroppedEvent.OutputObject>;

    filters: {
      
      'TokensAirdropped(address,uint256)': TypedContractEvent<TokensAirdroppedEvent.InputTuple, TokensAirdroppedEvent.OutputTuple, TokensAirdroppedEvent.OutputObject>;
      TokensAirdropped: TypedContractEvent<TokensAirdroppedEvent.InputTuple, TokensAirdroppedEvent.OutputTuple, TokensAirdroppedEvent.OutputObject>;
    
    };
  }