/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockERC20Fail__factory } from './MockERC20Fail__factory.js';
export { MockIdeaRegistryAuthorZero__factory } from './MockIdeaRegistryAuthorZero__factory.js';
export { MockReputationSystemDecreaseFail__factory } from './MockReputationSystemDecreaseFail__factory.js';
export { MockRolesAware__factory } from './MockRolesAware__factory.js';
export { MockRolesRegistryExpose__factory } from './MockRolesRegistryExpose__factory.js';
export { MockVotingSystemV2__factory } from './MockVotingSystemV2__factory.js';