/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MockReputationSystemDecreaseFailInterface extends Interface {
    getFunction(nameOrSignature: "decreaseReputation" | "increaseReputation"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'decreaseReputation', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'increaseReputation', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'decreaseReputation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'increaseReputation', data: BytesLike): Result;
  }

  

  export interface MockReputationSystemDecreaseFail extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockReputationSystemDecreaseFail;
    waitForDeployment(): Promise<this>;

    interface: MockReputationSystemDecreaseFailInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    decreaseReputation: TypedContractMethod<
      [arg0: AddressLike, ],
      [void],
      'view'
    >
    

    
    increaseReputation: TypedContractMethod<
      [arg0: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'decreaseReputation'): TypedContractMethod<
      [arg0: AddressLike, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'increaseReputation'): TypedContractMethod<
      [arg0: AddressLike, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }