/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { StealthAnnouncer, StealthAnnouncerInterface } from "../StealthAnnouncer.js";

  const _abi = [
  {
    "inputs": [],
    "name": "EmptyEphemeralPubKey",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidStealthAddress",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "schemeId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "stealthAddress",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "caller",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "bytes",
        "name": "ephemeralPubKey",
        "type": "bytes"
      },
      {
        "indexed": false,
        "internalType": "bytes",
        "name": "metadata",
        "type": "bytes"
      }
    ],
    "name": "Announcement",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "schemeId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "stealthAddress",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "ephemeralPubKey",
        "type": "bytes"
      },
      {
        "internalType": "bytes",
        "name": "metadata",
        "type": "bytes"
      }
    ],
    "name": "announce",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b5061024e8061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610029575f3560e01c80634d1f95831461002d575b5f5ffd5b61004061003b366004610129565b610042565b005b6001600160a01b038516610069576040516301696e0760e01b815260040160405180910390fd5b5f83900361008a576040516341c5c47d60e11b815260040160405180910390fd5b336001600160a01b0316856001600160a01b0316877f5f0eab8057630ba7676c49b4f21a0231414e79474595be8e4c432fbf6bf0f4e7878787876040516100d494939291906101e7565b60405180910390a4505050505050565b5f5f83601f8401126100f4575f5ffd5b50813567ffffffffffffffff81111561010b575f5ffd5b602083019150836020828501011115610122575f5ffd5b9250929050565b5f5f5f5f5f5f6080878903121561013e575f5ffd5b8635955060208701356001600160a01b038116811461015b575f5ffd5b9450604087013567ffffffffffffffff811115610176575f5ffd5b61018289828a016100e4565b909550935050606087013567ffffffffffffffff8111156101a1575f5ffd5b6101ad89828a016100e4565b979a9699509497509295939492505050565b81835281816020850137505f828201602090810191909152601f909101601f19169091010190565b604081525f6101fa6040830186886101bf565b828103602084015261020d8185876101bf565b97965050505050505056fea2646970667358221220119b539265da5e95373e37c1fe369ed24a60b4e1fd948315892439e16d2f973964736f6c634300081c0033";

  
      type StealthAnnouncerConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: StealthAnnouncerConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class StealthAnnouncer__factory extends ContractFactory {
    
      constructor(...args: StealthAnnouncerConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<StealthAnnouncer & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): StealthAnnouncer__factory {
      return super.connect(runner) as StealthAnnouncer__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): StealthAnnouncerInterface {
      return new Interface(_abi) as StealthAnnouncerInterface;
    }
    
    override attach(address: string | Addressable): StealthAnnouncer {
      return super.attach(address) as StealthAnnouncer;
    }
  static connect(address: string, runner?: ContractRunner | null): StealthAnnouncer {
      return new Contract(address, _abi, runner) as unknown as StealthAnnouncer;
    }
  }

  
  