/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockERC20Fail } from './MockERC20Fail.js';
export type { MockVotingSystemV2 } from './MockVotingSystemV2.js';