/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Album } from './Album.js';
export type { AlbumTracker } from './AlbumTracker.js';
export type { MusicShop } from './MusicShop.js';