/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../../common.js"
  import type { BrokenImpl, BrokenImplInterface } from "../../../../Time_Travel_Proxy/implementations/MockBroken.sol/BrokenImpl.js";

  const _abi = [
  {
    "inputs": [],
    "name": "healthCheck",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b5060c080601a5f395ff3fe6080604052348015600e575f5ffd5b50600436106026575f3560e01c8063b252720b14602a575b5f5ffd5b60306044565b604051901515815260200160405180910390f35b60405162461bcd60e51b8152602060048201526015602482015274213937b5b2b71034b6b83632b6b2b73a30ba34b7b760591b60448201525f9060640160405180910390fdfea26469706673582212204741d0e0df140d4f6b267e0154b37c030660c511b56e59e12b4edc904b389b9464736f6c634300081c0033";

  
      type BrokenImplConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: BrokenImplConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class BrokenImpl__factory extends ContractFactory {
    
      constructor(...args: BrokenImplConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<BrokenImpl & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): BrokenImpl__factory {
      return super.connect(runner) as BrokenImpl__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): BrokenImplInterface {
      return new Interface(_abi) as BrokenImplInterface;
    }
    
    override attach(address: string | Addressable): BrokenImpl {
      return super.attach(address) as BrokenImpl;
    }
  static connect(address: string, runner?: ContractRunner | null): BrokenImpl {
      return new Contract(address, _abi, runner) as unknown as BrokenImpl;
    }
  }

  
  