/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IProxy } from './IProxy.js';
export type { IUpgradeManager } from './IUpgradeManager.js';
export type { IUpgradePolicy } from './IUpgradePolicy.js';