/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface MockVotingSystemInterface extends Interface {
    getFunction(nameOrSignature: "distributeFunds" | "fundingPool" | "getWinningIdea" | "setFundingPool" | "setWinningIdea" | "winningIdeas"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'distributeFunds', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'fundingPool', values?: undefined): string;
encodeFunctionData(functionFragment: 'getWinningIdea', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setFundingPool', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setWinningIdea', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'winningIdeas', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'distributeFunds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundingPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWinningIdea', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFundingPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setWinningIdea', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'winningIdeas', data: BytesLike): Result;
  }

  

  export interface MockVotingSystem extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockVotingSystem;
    waitForDeployment(): Promise<this>;

    interface: MockVotingSystemInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    distributeFunds: TypedContractMethod<
      [roundId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fundingPool: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getWinningIdea: TypedContractMethod<
      [roundId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    setFundingPool: TypedContractMethod<
      [_fundingPool: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setWinningIdea: TypedContractMethod<
      [roundId: BigNumberish, ideaId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    winningIdeas: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'distributeFunds'): TypedContractMethod<
      [roundId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fundingPool'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getWinningIdea'): TypedContractMethod<
      [roundId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setFundingPool'): TypedContractMethod<
      [_fundingPool: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setWinningIdea'): TypedContractMethod<
      [roundId: BigNumberish, ideaId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'winningIdeas'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }