/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IVotingSystem, IVotingSystemInterface } from "../../../DAO_GRANT_SYSTEM/GrantManager.sol/IVotingSystem.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "roundId",
        "type": "uint256"
      }
    ],
    "name": "endVotingRound",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "winningIdeaId",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "roundId",
        "type": "uint256"
      }
    ],
    "name": "getRoundResults",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "winningIdeaId",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "totalVotes",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "roundId",
        "type": "uint256"
      },
      {
        "internalType": "uint256[]",
        "name": "ideaIds",
        "type": "uint256[]"
      }
    ],
    "name": "startVotingRound",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IVotingSystem__factory {
    static readonly abi = _abi;
    static createInterface(): IVotingSystemInterface {
      return new Interface(_abi) as IVotingSystemInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IVotingSystem {
      return new Contract(address, _abi, runner) as unknown as IVotingSystem;
    }
  }
  