/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IIdeaRegistry } from './IIdeaRegistry.js';
export type { VotingSystem } from './VotingSystem.js';