/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockBrokenSol from './MockBroken.sol/index.js';
export type { mockBrokenSol };
import type * as mockV1Sol from './MockV1.sol/index.js';
export type { mockV1Sol };
import type * as mockV2Sol from './MockV2.sol/index.js';
export type { mockV2Sol };
import type * as mockV3Sol from './MockV3.sol/index.js';
export type { mockV3Sol };
import type * as mockV4Sol from './MockV4.sol/index.js';
export type { mockV4Sol };
export type { HealthCheckable } from './HealthCheckable.js';
export type { MockImpl } from './MockImpl.js';