/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DEXGovernance } from './DEXGovernance.js';
export type { DEXTransparentProxyFactory } from './DEXTransparentProxyFactory.js';