/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener } from "../common.js"
  

  export interface IDEXGovernanceInterface extends Interface {
    

    getEvent(nameOrSignatureOrTopic: "ActionCancelled" | "ActionExecuted" | "ActionQueued"): EventFragment;

    

    
  }

  
    export namespace ActionCancelledEvent {
      export type InputTuple = [actionId: BytesLike];
      export type OutputTuple = [actionId: string];
      export interface OutputObject {actionId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ActionExecutedEvent {
      export type InputTuple = [actionId: BytesLike];
      export type OutputTuple = [actionId: string];
      export interface OutputObject {actionId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ActionQueuedEvent {
      export type InputTuple = [actionId: BytesLike, executeAfter: BigNumberish];
      export type OutputTuple = [actionId: string, executeAfter: bigint];
      export interface OutputObject {actionId: string, executeAfter: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IDEXGovernance extends BaseContract {
    
    connect(runner?: ContractRunner | null): IDEXGovernance;
    waitForDeployment(): Promise<this>;

    interface: IDEXGovernanceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    

    getEvent(key: 'ActionCancelled'): TypedContractEvent<ActionCancelledEvent.InputTuple, ActionCancelledEvent.OutputTuple, ActionCancelledEvent.OutputObject>;
getEvent(key: 'ActionExecuted'): TypedContractEvent<ActionExecutedEvent.InputTuple, ActionExecutedEvent.OutputTuple, ActionExecutedEvent.OutputObject>;
getEvent(key: 'ActionQueued'): TypedContractEvent<ActionQueuedEvent.InputTuple, ActionQueuedEvent.OutputTuple, ActionQueuedEvent.OutputObject>;

    filters: {
      
      'ActionCancelled(bytes32)': TypedContractEvent<ActionCancelledEvent.InputTuple, ActionCancelledEvent.OutputTuple, ActionCancelledEvent.OutputObject>;
      ActionCancelled: TypedContractEvent<ActionCancelledEvent.InputTuple, ActionCancelledEvent.OutputTuple, ActionCancelledEvent.OutputObject>;
    

      'ActionExecuted(bytes32)': TypedContractEvent<ActionExecutedEvent.InputTuple, ActionExecutedEvent.OutputTuple, ActionExecutedEvent.OutputObject>;
      ActionExecuted: TypedContractEvent<ActionExecutedEvent.InputTuple, ActionExecutedEvent.OutputTuple, ActionExecutedEvent.OutputObject>;
    

      'ActionQueued(bytes32,uint256)': TypedContractEvent<ActionQueuedEvent.InputTuple, ActionQueuedEvent.OutputTuple, ActionQueuedEvent.OutputObject>;
      ActionQueued: TypedContractEvent<ActionQueuedEvent.InputTuple, ActionQueuedEvent.OutputTuple, ActionQueuedEvent.OutputObject>;
    
    };
  }