/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, FunctionFragment, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener } from "../common.js"
  

  export interface IFeeCollectorInterface extends Interface {
    

    getEvent(nameOrSignatureOrTopic: "FeeWithdrawn"): EventFragment;

    

    
  }

  
    export namespace FeeWithdrawnEvent {
      export type InputTuple = [token: AddressLike, recipient: AddressLike, amount: BigNumberish];
      export type OutputTuple = [token: string, recipient: string, amount: bigint];
      export interface OutputObject {token: string, recipient: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IFeeCollector extends BaseContract {
    
    connect(runner?: ContractRunner | null): IFeeCollector;
    waitForDeployment(): Promise<this>;

    interface: IFeeCollectorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    

    getEvent(key: 'FeeWithdrawn'): TypedContractEvent<FeeWithdrawnEvent.InputTuple, FeeWithdrawnEvent.OutputTuple, FeeWithdrawnEvent.OutputObject>;

    filters: {
      
      'FeeWithdrawn(address,address,uint256)': TypedContractEvent<FeeWithdrawnEvent.InputTuple, FeeWithdrawnEvent.OutputTuple, FeeWithdrawnEvent.OutputObject>;
      FeeWithdrawn: TypedContractEvent<FeeWithdrawnEvent.InputTuple, FeeWithdrawnEvent.OutputTuple, FeeWithdrawnEvent.OutputObject>;
    
    };
  }