/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { MockImpl, MockImplInterface } from "../../../Time_Travel_Proxy/implementations/MockImpl.js";

  const _abi = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "newValue",
        "type": "uint256"
      }
    ],
    "name": "ValueChanged",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "iterations",
        "type": "uint256"
      }
    ],
    "name": "expensiveFunction",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getValue",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "healthCheck",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "isHealthy",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "payableFunction",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "revertingFunction",
    "outputs": [],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bool",
        "name": "health",
        "type": "bool"
      }
    ],
    "name": "setHealth",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_value",
        "type": "uint256"
      }
    ],
    "name": "setValue",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "interfaceId",
        "type": "bytes4"
      }
    ],
    "name": "supportsInterface",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "testFunction",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "value",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x60806040526001805460ff191681179055348015601a575f5ffd5b50602a5f556103578061002c5f395ff3fe60806040526004361061009a575f3560e01c80639afb7b2f116100625780639afb7b2f1461012a578063b23fe02314610157578063b252720b14610176578063c84f59b41461018d578063e16b4a9b146101a1578063e4020804146101b4575f5ffd5b806301ffc9a71461009e57806320965255146100d25780633fa4f245146100ef5780634a6a7407146101035780635524107714610109575b5f5ffd5b3480156100a9575f5ffd5b506100bd6100b836600461029e565b6101cd565b60405190151581526020015b60405180910390f35b3480156100dd575f5ffd5b505f545b6040519081526020016100c9565b3480156100fa575f5ffd5b506100e15f5481565b346100e1565b348015610114575f5ffd5b506101286101233660046102cc565b610203565b005b348015610135575f5ffd5b506101286101443660046102e3565b6001805460ff1916911515919091179055565b348015610162575f5ffd5b506100e16101713660046102cc565b61023d565b348015610181575f5ffd5b5060015460ff166100bd565b348015610198575f5ffd5b50610128610264565b3480156101ac575f5ffd5b50602a6100e1565b3480156101bf575f5ffd5b506001546100bd9060ff1681565b5f6301ffc9a760e01b6001600160e01b0319831614806101fd57506302468acf60e31b6001600160e01b03198316145b92915050565b5f8190556040518181527f93fe6d397c74fdf1402a8b72e47b68512f0510d7b98a4bc4cbdf6ac7108b3c599060200160405180910390a150565b5f80805b8381101561025d576102538183610302565b9150600101610241565b5092915050565b60405162461bcd60e51b815260206004820152600b60248201526a135bd8dac81c995d995c9d60aa1b604482015260640160405180910390fd5b5f602082840312156102ae575f5ffd5b81356001600160e01b0319811681146102c5575f5ffd5b9392505050565b5f602082840312156102dc575f5ffd5b5035919050565b5f602082840312156102f3575f5ffd5b813580151581146102c5575f5ffd5b808201808211156101fd57634e487b7160e01b5f52601160045260245ffdfea264697066735822122058852509ffcfd72dd9b5128c663d71ccd552a8645e13c13eaa405a84547cc09a64736f6c634300081c0033";

  
      type MockImplConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockImplConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockImpl__factory extends ContractFactory {
    
      constructor(...args: MockImplConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockImpl & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockImpl__factory {
      return super.connect(runner) as MockImpl__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockImplInterface {
      return new Interface(_abi) as MockImplInterface;
    }
    
    override attach(address: string | Addressable): MockImpl {
      return super.attach(address) as MockImpl;
    }
  static connect(address: string, runner?: ContractRunner | null): MockImpl {
      return new Contract(address, _abi, runner) as unknown as MockImpl;
    }
  }

  
  