/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../../common.js"
  

  export interface IVoterProgressionInterface extends Interface {
    getFunction(nameOrSignature: "getProgressionStatus" | "getWinningVotes" | "grantCuratorRole" | "grantReviewerRole" | "hasRoleCurator" | "hasRoleReviewer" | "qualifiesForCurator" | "qualifiesForReviewer" | "registerWinningVote" | "resetProgression"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ProgressionReset" | "RoleGranted" | "WinningVoteRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'getProgressionStatus', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getWinningVotes', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantCuratorRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantReviewerRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRoleCurator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRoleReviewer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'qualifiesForCurator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'qualifiesForReviewer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registerWinningVote', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'resetProgression', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'getProgressionStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWinningVotes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantCuratorRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantReviewerRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRoleCurator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRoleReviewer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'qualifiesForCurator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'qualifiesForReviewer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerWinningVote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resetProgression', data: BytesLike): Result;
  }

  
    export namespace ProgressionResetEvent {
      export type InputTuple = [voter: AddressLike];
      export type OutputTuple = [voter: string];
      export interface OutputObject {voter: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [voter: AddressLike, role: BytesLike];
      export type OutputTuple = [voter: string, role: string];
      export interface OutputObject {voter: string, role: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WinningVoteRegisteredEvent {
      export type InputTuple = [voter: AddressLike, totalWinningVotes: BigNumberish];
      export type OutputTuple = [voter: string, totalWinningVotes: bigint];
      export interface OutputObject {voter: string, totalWinningVotes: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IVoterProgression extends BaseContract {
    
    connect(runner?: ContractRunner | null): IVoterProgression;
    waitForDeployment(): Promise<this>;

    interface: IVoterProgressionInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getProgressionStatus: TypedContractMethod<
      [voter: AddressLike, ],
      [[bigint, boolean, boolean, bigint, bigint] & {winningVotes: bigint, isCurator: boolean, isReviewer: boolean, votesToCurator: bigint, votesToReviewer: bigint }],
      'view'
    >
    

    
    getWinningVotes: TypedContractMethod<
      [voter: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    grantCuratorRole: TypedContractMethod<
      [voter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    grantReviewerRole: TypedContractMethod<
      [voter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRoleCurator: TypedContractMethod<
      [voter: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    hasRoleReviewer: TypedContractMethod<
      [voter: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    qualifiesForCurator: TypedContractMethod<
      [voter: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    qualifiesForReviewer: TypedContractMethod<
      [voter: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    registerWinningVote: TypedContractMethod<
      [voter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    resetProgression: TypedContractMethod<
      [voter: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getProgressionStatus'): TypedContractMethod<
      [voter: AddressLike, ],
      [[bigint, boolean, boolean, bigint, bigint] & {winningVotes: bigint, isCurator: boolean, isReviewer: boolean, votesToCurator: bigint, votesToReviewer: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getWinningVotes'): TypedContractMethod<
      [voter: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'grantCuratorRole'): TypedContractMethod<
      [voter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'grantReviewerRole'): TypedContractMethod<
      [voter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRoleCurator'): TypedContractMethod<
      [voter: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'hasRoleReviewer'): TypedContractMethod<
      [voter: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'qualifiesForCurator'): TypedContractMethod<
      [voter: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'qualifiesForReviewer'): TypedContractMethod<
      [voter: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'registerWinningVote'): TypedContractMethod<
      [voter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resetProgression'): TypedContractMethod<
      [voter: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ProgressionReset'): TypedContractEvent<ProgressionResetEvent.InputTuple, ProgressionResetEvent.OutputTuple, ProgressionResetEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'WinningVoteRegistered'): TypedContractEvent<WinningVoteRegisteredEvent.InputTuple, WinningVoteRegisteredEvent.OutputTuple, WinningVoteRegisteredEvent.OutputObject>;

    filters: {
      
      'ProgressionReset(address)': TypedContractEvent<ProgressionResetEvent.InputTuple, ProgressionResetEvent.OutputTuple, ProgressionResetEvent.OutputObject>;
      ProgressionReset: TypedContractEvent<ProgressionResetEvent.InputTuple, ProgressionResetEvent.OutputTuple, ProgressionResetEvent.OutputObject>;
    

      'RoleGranted(address,bytes32)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'WinningVoteRegistered(address,uint256)': TypedContractEvent<WinningVoteRegisteredEvent.InputTuple, WinningVoteRegisteredEvent.OutputTuple, WinningVoteRegisteredEvent.OutputObject>;
      WinningVoteRegistered: TypedContractEvent<WinningVoteRegisteredEvent.InputTuple, WinningVoteRegisteredEvent.OutputTuple, WinningVoteRegisteredEvent.OutputObject>;
    
    };
  }