/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockIdeaRegistryAuthorZero, MockIdeaRegistryAuthorZeroInterface } from "../../Mocks/MockIdeaRegistryAuthorZero.js";

  const _abi = [
  {
    "inputs": [],
    "name": "author",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "getIdeaAuthor",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "getStatus",
    "outputs": [
      {
        "internalType": "enum IdeaStatus",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "newAuthor",
        "type": "address"
      }
    ],
    "name": "setAuthor",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "enum IdeaStatus",
        "name": "newStatus",
        "type": "uint8"
      }
    ],
    "name": "setStatus",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "status",
    "outputs": [
      {
        "internalType": "enum IdeaStatus",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "enum IdeaStatus",
        "name": "",
        "type": "uint8"
      }
    ],
    "name": "updateStatus",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x60806040525f805460ff60a01b1916600160a11b1790553480156020575f5ffd5b506103858061002e5f395ff3fe608060405234801561000f575f5ffd5b506004361061007a575f3560e01c806350ce6b181161005857806350ce6b18146100ce5780635c622a0e146100f9578063a05f41a41461010c578063a6c3e6b91461011f575f5ffd5b8063200d2ed21461007e5780632e49d78b146100a75780633a1b3d31146100bc575b5f5ffd5b5f5461009190600160a01b900460ff1681565b60405161009e919061028f565b60405180910390f35b6100ba6100b53660046102c8565b610131565b005b6100ba6100ca3660046102e8565b5050565b6100e16100dc366004610312565b610186565b6040516001600160a01b03909116815260200161009e565b610091610107366004610312565b6101c0565b6100ba61011a366004610329565b6101fb565b5f546100e1906001600160a01b031681565b61015a7f63f58d4d942853fc737ea7fdccce5368fe84f3a1165cf22405c2ae9130a86581610245565b5f805482919060ff60a01b1916600160a01b83600581111561017e5761017e61027b565b021790555050565b5f6101b07fc658d2a4fcea46538016f772e3004b7890e62de8eff331f59067bdb96402b041610245565b50505f546001600160a01b031690565b5f6101ea7f7c3f4902ff1961c38d31907fbf186e4b5c02b69913878eba53ce6dabffe4236d610245565b50505f54600160a01b900460ff1690565b6102247f53a19753023e6722e8fbdbec97ac8af8677d3ab3f19e760dc135c48560991105610245565b5f80546001600160a01b0319166001600160a01b0392909216919091179055565b61024e81610251565b50565b60405181815273c0bec0bec0bec0bec0bec0bec0bec0bec0bec0be905f80602083855afa50505050565b634e487b7160e01b5f52602160045260245ffd5b60208101600683106102af57634e487b7160e01b5f52602160045260245ffd5b91905290565b8035600681106102c3575f5ffd5b919050565b5f602082840312156102d8575f5ffd5b6102e1826102b5565b9392505050565b5f5f604083850312156102f9575f5ffd5b82359150610309602084016102b5565b90509250929050565b5f60208284031215610322575f5ffd5b5035919050565b5f60208284031215610339575f5ffd5b81356001600160a01b03811681146102e1575f5ffdfea26469706673582212204c5ec98f955732d6329c8dc299c342c1f0f882a2d51caa62d3ccf9ea5a5096b464736f6c634300081c0033";

  
      type MockIdeaRegistryAuthorZeroConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockIdeaRegistryAuthorZeroConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockIdeaRegistryAuthorZero__factory extends ContractFactory {
    
      constructor(...args: MockIdeaRegistryAuthorZeroConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockIdeaRegistryAuthorZero & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockIdeaRegistryAuthorZero__factory {
      return super.connect(runner) as MockIdeaRegistryAuthorZero__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockIdeaRegistryAuthorZeroInterface {
      return new Interface(_abi) as MockIdeaRegistryAuthorZeroInterface;
    }
    
    override attach(address: string | Addressable): MockIdeaRegistryAuthorZero {
      return super.attach(address) as MockIdeaRegistryAuthorZero;
    }
  static connect(address: string, runner?: ContractRunner | null): MockIdeaRegistryAuthorZero {
      return new Contract(address, _abi, runner) as unknown as MockIdeaRegistryAuthorZero;
    }
  }

  
  