/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFundingPool } from './IFundingPool.js';
export type { IGrantManager } from './IGrantManager.js';
export type { IIdeaRegistry } from './IIdeaRegistry.js';
export type { IReputationSystem } from './IReputationSystem.js';
export type { IRoles } from './IRoles.js';
export type { IVoterProgression } from './IVoterProgression.js';
export type { IVotingSystem } from './IVotingSystem.js';