/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, FunctionFragment, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener } from "../../common.js"
  

  export interface IDEXTransparentProxyFactoryInterface extends Interface {
    

    getEvent(nameOrSignatureOrTopic: "ProxyStackDeployed"): EventFragment;

    

    
  }

  
    export namespace ProxyStackDeployedEvent {
      export type InputTuple = [implementation: AddressLike, proxyAdmin: AddressLike, proxy: AddressLike];
      export type OutputTuple = [implementation: string, proxyAdmin: string, proxy: string];
      export interface OutputObject {implementation: string, proxyAdmin: string, proxy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IDEXTransparentProxyFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): IDEXTransparentProxyFactory;
    waitForDeployment(): Promise<this>;

    interface: IDEXTransparentProxyFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    

    getEvent(key: 'ProxyStackDeployed'): TypedContractEvent<ProxyStackDeployedEvent.InputTuple, ProxyStackDeployedEvent.OutputTuple, ProxyStackDeployedEvent.OutputObject>;

    filters: {
      
      'ProxyStackDeployed(address,address,address)': TypedContractEvent<ProxyStackDeployedEvent.InputTuple, ProxyStackDeployedEvent.OutputTuple, ProxyStackDeployedEvent.OutputObject>;
      ProxyStackDeployed: TypedContractEvent<ProxyStackDeployedEvent.InputTuple, ProxyStackDeployedEvent.OutputTuple, ProxyStackDeployedEvent.OutputObject>;
    
    };
  }